.eslintrc, auto-claim/index.js, auto-claim/server.js, auto-claim/service-worker.js, gulpfile.js, offline-fallback/index.js, package.json
Removing strict (assumes babel) and id-length (for loops are not the same without i)
More to add/remove?
r? @TimAbraldes @franciov
=> eslint rules

cache-then-network/index.js
See https://bugzilla.mozilla.org/show_bug.cgi?id=1216373
Fixes #16
=> Use a cache buster in cache-then-network fetch

push-payload/index.html, push-payload/index.js, push-payload/manifest.json, push-payload/server.js, push-payload/service-worker.js
This doesn't work in Chrome currently (until https://code.google.com/p/chromium/issues/detail?id=486040 is fixed).
=> Push notification with payload recipe

api-analytics/README.md, api-analytics/index.html, api-analytics/index.js, api-analytics/report.html, api-analytics/server.js, api-analytics/worker.js
Fixes #22 
@zalun @darkwing  , do you want to take a look?
=> Api analytics

json-cache/README.md, offline-status/README.md
Important I get these in while still fresh in my mind.
=> Add README.md files for my demos

push-clients/index.html, push-clients/index.js, push-clients/manifest.json, push-clients/server.js, push-clients/service-worker.js
This currently doesn't completely work in Chrome.
Indeed, `clients.openWindow('./push-clients/index.html')` opens `http://localhost:3003/push-clients/index.html` in Firefox, but `http://localhost:3003/push-clients/push-clients/index.html` in Chrome.
https://bugzilla.mozilla.org/show_bug.cgi?id=1222097
=> Push notification with clients management recipe

src/tpl/index.html
=> replace Blagh

api-analytics/README.md, cache-then-network/README.md, gulpfile.js, immediate-claim/README.md, json-cache/README.md, live-flowchart/README.md, message-relay/README.md, offline-fallback/README.md, offline-status/README.md, parseRecipes.js, push-clients/README.md, push-payload/README.md, push-rich/README.md, push-simple/README.md, push-subscription-management/README.md
The summaries still probably need some work, but they're getting better.
=> More cleanup

src/css/style.css, src/js/layout.js
Added some minor design tweaks and color to the design of SWC
=> Minor style updates for cookbook

src/css/style.css, src/tpl/index.html
We did a lot of logging to console in these demos so we should encourage developers to checkout the console messages as they come by.
=> Add message to intro about opening DevTools

fetching/README.md, fetching/index.html, fetching/index.js, fetching/service-worker.js
fetching all types of the content
* DOM element
* direct fetch command
* proxy (client "thinks" request is done to local resource)
Fetch request method
* cors/nocors
Resource
* http
* https with allow-origin headers
* https without allow-origin headers
=> fetching recipe

src/css/style.css, src/tpl/index.html, src/tpl/layout.html
This is a first step.  I will be adding Tabzilla and maybe something else in the sidebar as well.
=> Resolve #81 - Add basic attribution

push-quota/README.md, push-quota/index.html, push-quota/index.js, push-quota/manifest.json, push-quota/server.js, push-quota/service-worker.js
=> Quota example

.travis.yml, package.json, parseRecipes.js
startsWith and endsWith are unavailable on Node 0.12.
=> Include polyfills for startsWith and endsWith

.travis.yml, package.json, parseRecipes.js
Reverts mozilla/serviceworker-cookbook#66
Hopefully this will fix the Heroku build.
=> Revert "Include polyfills for startsWith and endsWith"

src/css/style.css
- Softened the level blocks 
- Added hover style for sidebar links
=> Minor style updates for the sidebar

.travis.yml
I'm too curious to try this again. Don't mind it, I'll take care of reverting if it makes Heroku fail.
=> Test/build on Travis CI with Node.js 0.12 as well; only deploy with Node.js 4

api-analytics/README.md, cache-then-network/README.md, fetching/README.md, immediate-claim/README.md, json-cache/README.md, live-flowchart/README.md, message-relay/README.md, offline-fallback/README.md, offline-status/README.md, push-clients/README.md, push-payload/README.md, push-quota/README.md, push-replace/README.md, push-rich/README.md, push-simple/README.md, push-subscription-management/README.md
Fixes #92.
Suggestions welcome on how to categorize the recipes where I put "?".
=> Add category field to recipes

gulpfile.js, parseRecipes.js, src/css/style.css, src/tpl/layout.html
=> List by category

src/css/style.css, src/tpl/layout.html
- use meta
- wrap the tabs at the top
=> Improve mobile viewing.

README.md
=> Adding Jake Archibald's 'Offline Cookbook' resource

dependency-injector/README.md, dependency-injector/actual-controller.js, dependency-injector/actual-dialogs.js, dependency-injector/bootstrap.js, dependency-injector/default-mapping.js, dependency-injector/index.html, dependency-injector/injector.js, dependency-injector/mock-dialogs.js, dependency-injector/production-sw.js, dependency-injector/testing-sw.js
Fix #17 
It shows a use case about using service workers as dependency injectors mapping abstract resources with real ones. @marco-c or @darkwing do you want to take a look?
=> Dependency injection

parseRecipes.js, src/css/style.css, src/js/layout.js, src/tpl/demo.html, src/tpl/layout.html
Not sure how I feel about this.  I added a `<button>` so that you can tab to the icon but....I don't know...
=> Resolve 62 - Allow opening demo in new window

dependency-injector/index.html
=> Clarifying the demo in the dependency injector

fetching/index.js, virtual-server/index.js, virtual-server/service-worker.js
=> Fix lint warnings

render-store/README.md, render-store/index.html, render-store/index.js, render-store/pokemon.html, render-store/pokemon.js, render-store/service-worker.js
Fix #20 
@darkwing do you want to take a look at this?
=> Render store

push-clients/service-worker.js
Fixes regression from the cookbook page restructuring.
=> Make push-client recipe open the demo page when the user clicks on a notification

src/css/style.css
=> Resolve 158 - Make 'demo' and 'readme' line up

_recipe_template/README.md, _recipe_template/service-worker.js, api-analytics/README.md, cache-from-zip/README.md, cache-then-network/README.md, dependency-injector/README.md, fetching/README.md, immediate-claim/README.md, json-cache/README.md, live-flowchart/README.md, message-relay/README.md, offline-fallback/README.md, offline-status/README.md, push-subscription-management/README.md, render-store/README.md, request-deferrer/README.md, virtual-server/README.md
Using sentence case for consistency and other minor updates.
=> README cleanup for consistency

_recipe_template/README.md, api-analytics/README.md, cache-from-zip/README.md, dependency-injector/README.md, gulpfile.js, parseRecipes.js, render-store/README.md, request-deferrer/README.md, virtual-server/README.md
I also changed "More than Offline" to "Beyond Offline"
=> Resolve #157 - Create sort order for sidebar

src/css/style.css
=> Possible alternate design

src/css/style.css
Minor improvement to the difficulty badges to make them appear less gray.
=> Increase difficulty badge text contrast

src/js/layout.js
Initially discussed in https://github.com/mozilla/serviceworker-cookbook/issues/108#issuecomment-158184177, https://github.com/mozilla/serviceworker-cookbook/issues/108#issuecomment-158192392 and https://github.com/mozilla/serviceworker-cookbook/issues/108#issuecomment-158318447
=> remember nav bar visibility using localstorage

.eslintrc, dependency-injector/actual-dialogs.js, dependency-injector/mock-dialogs.js, package.json, request-deferrer/service-worker.js, virtual-server/service-worker.js
I've updated eslint-config-airbnb, modifying some of the rules they added with what I prefer.
=> Update eslint-config-airbnb to version 4

push-clients/server.js, push-payload/server.js, push-quota/server.js, push-replace/server.js, push-rich/server.js, push-simple/server.js
=> Make all requests return a status code

package.json
This fixes a problem with unicode characters in the payload (https://github.com/marco-c/web-push/issues/73).
=> Update web-push module to version 1

src/tpl/layout.html
=> Add current recipe name to the title

server.js
=> Set max-age header for service workers

server.js, src/tpl/layout.html
https://github.com/mozilla/serviceworker-cookbook/issues/190
=> Fix #190 - Remove index.html from homepage URL

gulpfile.js, parseRecipes.js, src/css/style.css, src/tpl/category.html, src/tpl/layout.html
Fixes https://github.com/mozilla/serviceworker-cookbook/issues/202
=> Add category landing pages

gulpfile.js
=> Fixed a gulp-docco bug from configuration

.travis.yml, package.json, push-clients/server.js, push-get-payload/server.js, push-payload/server.js, push-quota/server.js, push-replace/server.js, push-rich/server.js, push-simple/server.js, push-subscription-management/server.js
Fix #245 
@marco-c since I changed Push-related recipes, do you mind to take a look, please?
=> Issue 245 update dependencies

src/tpl/layout.html
=> Added category to the recipe title

message-relay/service-worker.js
=> Removed warning about Chrome is message relay

src/tpl/index.html
Fix #280 
@jensimmons do you think this is better?
=> Removed web app wording in favour of web site.

src/css/style.css, src/tpl/demo.html
=> Fixing scroll behaviour for non iOS devices

push-clients/index.js, push-clients/server.js, push-get-payload/index.js, push-payload/index.js, push-quota/index.js, push-replace/index.js, push-rich/index.js, push-simple/index.js
=> Wait for serviceWorker.ready in push recipes

src/css/style.css
=> Add iOS-specific styles to make scrolling smoother

package.json
=> Updated dependencies!
